"""CLI + composition root.

This is the *only* place that names concrete A-stage implementations. Migrating
to B2 is a localized edit here:

    # A stage (today):
    store = GitMarkdownStore(vault_root)
    deduper = StringMatchDeduper(store, fuzzy_threshold=args.fuzzy)

    # B2 stage (later) -- same Protocols, new classes:
    store = PostgresStore(dsn)
    deduper = PgVectorDeduper(dsn, embed_model="...")

ContributionService and everything it depends on are untouched.

Usage:
    python -m vault_contrib.cli contribute \\
        --vault ./myvault --by agent-1 \\
        --title "Two-phase tick updates" \\
        --body "Read into a buffer, then commit, so order doesn't bias..." \\
        --tags simulation,determinism

    python -m vault_contrib.cli list --vault ./myvault
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

from .dedup_string import StringMatchDeduper
from .models import Note, Policy
from .service import ContributionService
from .store_git import GitMarkdownStore, _deserialize
from . import vault_frontmatter as vf

# The central vault all projects point at when --vault is omitted: the
# KNOWLEDGE_VAULT env var, else ~/knowledge-vault. Resolved (~ and $VARs
# expanded) so a literal "~" directory can never be created.
DEFAULT_VAULT = "~/knowledge-vault"


def _resolve_vault(path: str | None) -> Path:
    raw = path or os.environ.get("KNOWLEDGE_VAULT") or DEFAULT_VAULT
    return Path(os.path.expandvars(os.path.expanduser(raw)))


def _build_service(args: argparse.Namespace) -> ContributionService:
    store = GitMarkdownStore(_resolve_vault(args.vault), auto_commit=not args.no_commit)
    deduper = StringMatchDeduper(store, fuzzy_threshold=args.fuzzy)
    policy = Policy(flag_at=args.flag_at)
    return ContributionService(deduper, store, policy)


def _cmd_contribute(args: argparse.Namespace) -> int:
    service = _build_service(args)
    tags = [t.strip() for t in args.tags.split(",") if t.strip()] if args.tags else []
    result = service.contribute(
        title=args.title,
        body=args.body,
        contributed_by=args.by,
        tags=tags,
        source=args.source,
        client_run_id=args.run_id,
    )
    print(
        json.dumps(
            {
                "status": result.status,
                "note_id": result.note_id,
                "message": result.message,
                "errors": result.errors,
                "similars": [
                    {"note_id": c.note_id, "title": c.title, "score": round(c.score, 4)}
                    for c in result.similars
                ],
            },
            indent=2,
        )
    )
    # Non-zero exit on a non-write outcome so scripts/agents can branch on it.
    return 0 if result.status in {"inserted", "linked"} else 1


def _cmd_list(args: argparse.Namespace) -> int:
    store = GitMarkdownStore(_resolve_vault(args.vault), auto_commit=False)
    wanted = set(args.tag or [])  # AND semantics across repeated --tag
    for note in store.iter_notes():
        if wanted and not wanted <= set(note.tags):
            continue
        print(f"{note.id}  {note.title}  [{', '.join(note.tags)}]  by {note.contributed_by}")
    return 0


def render_index(entries: list[tuple[str, Note]]) -> str:
    """Markdown index grouping notes by tag. `entries` pairs each note with its
    vault-relative path (e.g. "notes/two-phase-tick-updates.md") for linking.

    Flat storage + this generated view gives the grouped-browsing benefit of
    folders without the single-hierarchy lock-in: a note appears under *every*
    tag it carries. Untagged notes collect under "(untagged)".
    """
    by_tag: dict[str, list[tuple[str, Note]]] = {}
    for relpath, note in entries:
        for tag in note.tags or ["(untagged)"]:
            by_tag.setdefault(tag, []).append((relpath, note))

    lines = [f"# Knowledge Vault index", "", f"_{len(entries)} notes. Generated by `vault_contrib.cli index`._", ""]
    for tag in sorted(by_tag):
        group = sorted(by_tag[tag], key=lambda e: e[1].title.lower())
        lines.append(f"## {tag} ({len(group)})")
        for relpath, note in group:
            lines.append(f"- [{note.title}]({relpath}) — by {note.contributed_by}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _cmd_index(args: argparse.Namespace) -> int:
    vault = _resolve_vault(args.vault)
    store = GitMarkdownStore(vault, auto_commit=False)
    entries = [
        (path.relative_to(vault).as_posix(),
         _deserialize(path.read_text(encoding="utf-8")))
        for path in sorted(store.notes_dir.glob("*.md"))
    ]
    out = vault / "INDEX.md"
    out.write_text(render_index(entries), encoding="utf-8")
    print(f"Wrote {out} ({len(entries)} notes).")
    return 0


def _iter_normalize_targets(vault: Path) -> list[Path]:
    notes_dir = vault / "notes"
    if not notes_dir.is_dir():
        return []
    return [
        path
        for path in sorted(notes_dir.glob("*.md"))
        if path.name not in {"INDEX.md", "README.md"}
    ]


def _cmd_normalize(args: argparse.Namespace) -> int:
    vault = _resolve_vault(args.vault)
    offenders: list[Path] = []
    errors: list[tuple[Path, str]] = []
    rewritten: list[Path] = []

    for path in _iter_normalize_targets(vault):
        text = path.read_text(encoding="utf-8")
        try:
            canonical = vf.canonicalize(text.replace("\r\n", "\n"))
        except ValueError as exc:
            errors.append((path, str(exc)))
            continue
        if canonical == text:
            continue
        if args.check:
            offenders.append(path)
        else:
            path.write_text(canonical, encoding="utf-8")
            rewritten.append(path)

    for path, message in errors:
        print(
            f"SKIP (unparseable): {path.relative_to(vault).as_posix()} -- {message}",
            file=sys.stderr,
        )

    if args.check:
        if offenders:
            print(f"{len(offenders)} note(s) not in canonical style:")
            for path in offenders:
                print(f"  {path.relative_to(vault).as_posix()}")
            print("\nrun: python -m vault_contrib.cli normalize --vault <vault> to fix")
            return 1
        print("all notes canonical")
        return 1 if errors else 0

    if rewritten:
        print(f"rewrote {len(rewritten)} note(s):")
        for path in rewritten:
            print(f"  {path.relative_to(vault).as_posix()}")
    else:
        print("nothing to do; all notes already canonical")
    return 1 if errors else 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="vault_contrib", description=__doc__)
    sub = p.add_subparsers(dest="command", required=True)

    c = sub.add_parser("contribute", help="add a note (with dedup)")
    c.add_argument("--vault", default=None,
                   help="path to the vault repo (default: $KNOWLEDGE_VAULT, "
                        "else ~/knowledge-vault)")
    c.add_argument("--title", required=True)
    c.add_argument("--body", required=True)
    c.add_argument("--by", required=True,
                   help="contributor id; namespaced by convention as "
                        "agent:<id> or human:<name>")
    c.add_argument("--tags", default="", help="comma-separated tags")
    c.add_argument("--source", default=None, help="provenance, e.g. a URL")
    c.add_argument("--run-id", default=None, dest="run_id",
                   help="idempotency key: reusing it makes a retry a no-op")
    c.add_argument("--flag-at", type=float, default=0.85, dest="flag_at",
                   help="similarity at/above which a note is flagged for review")
    c.add_argument("--fuzzy", type=float, default=None,
                   help="enable fuzzy title match at this ratio (else exact only)")
    c.add_argument("--no-commit", action="store_true", help="skip git auto-commit")
    c.set_defaults(func=_cmd_contribute)

    l = sub.add_parser("list", help="list active notes in the vault")
    l.add_argument("--vault", default=None,
                   help="path to the vault repo (default: $KNOWLEDGE_VAULT, "
                        "else ~/knowledge-vault)")
    l.add_argument("--tag", action="append",
                   help="only notes with this tag; repeat for AND")
    l.set_defaults(func=_cmd_list)

    i = sub.add_parser("index", help="write a tag-grouped INDEX.md to the vault")
    i.add_argument("--vault", default=None,
                   help="path to the vault repo (default: $KNOWLEDGE_VAULT, "
                        "else ~/knowledge-vault)")
    i.set_defaults(func=_cmd_index)

    n = sub.add_parser("normalize", help="canonicalize active note frontmatter")
    n.add_argument("--vault", default=None,
                   help="path to the vault repo (default: $KNOWLEDGE_VAULT, "
                        "else ~/knowledge-vault)")
    n.add_argument("--check", action="store_true",
                   help="report non-canonical notes without rewriting")
    n.set_defaults(func=_cmd_normalize)

    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
