"""Generate a Map-of-Content (MoC) index note for a Human-vault folder.

The agent layer has ``vault_contrib index`` (flat notes grouped by tag). The
Human layer is folder-organized instead, so this renders a MoC that mirrors the
folder tree: notes directly in the target folder are listed first, then one
section per immediate subfolder (each collecting everything beneath it). Links
are Obsidian wikilinks by note title, so the index works from any location.

The output is a normal ``Type: MoC`` note (MoC is a universal type, allowed in
any folder). It is regenerated wholesale on each run; ``CreatedAt`` is preserved
from an existing index so only ``LastUpdated`` churns.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import PurePosixPath
from typing import Iterable

from .frontmatter_scan import NoteRecord


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def render_moc(
    rel_path: str,
    records: Iterable[NoteRecord],
    *,
    created: str | None = None,
    now: str | None = None,
) -> str:
    """Render the MoC note for the folder ``rel_path`` (vault-relative posix).

    ``records`` are the notes to include (already filtered to this folder). Each
    is bucketed by its first path component below ``rel_path`` — "" meaning the
    note sits directly in the folder.
    """
    now = now or utc_now()
    created = created or now
    prefix = rel_path.rstrip("/") + "/"
    title = PurePosixPath(rel_path).name or rel_path

    groups: dict[str, list[str]] = {}
    for rec in records:
        rp = rec.rel_path
        if not rp.startswith(prefix):
            continue
        rest = rp[len(prefix):]
        key = rest.split("/", 1)[0] if "/" in rest else ""
        groups.setdefault(key, []).append(PurePosixPath(rp).stem)

    total = sum(len(v) for v in groups.values())
    lines = [
        "---", "Type: MoC", "Status:",
        f"CreatedAt: {created}", f"LastUpdated: {now}",
        "tags:", "aliases:", "---",
        f"# {title}", "",
        "_Generated by `vault_governance.cli moc` - regenerate to update; "
        "manual edits are overwritten._", "",
        f"_{total} notes._", "",
    ]

    for stem in sorted(groups.get("", []), key=str.lower):
        lines.append(f"- [[{stem}]]")
    if groups.get(""):
        lines.append("")

    for key in sorted((k for k in groups if k), key=str.lower):
        items = sorted(groups[key], key=str.lower)
        lines.append(f"## {key} ({len(items)})")
        lines.append("")
        for stem in items:
            lines.append(f"- [[{stem}]]")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
